USE ud_pg;

INSERT INTO departamento VALUES ('Bgta', 'Bogotá D.C.', DEFAULT, DEFAULT);
INSERT INTO departamento VALUES ('Cal', 'Caldas', DEFAULT, DEFAULT);
INSERT INTO departamento VALUES ('Vcauc', 'Valle del Cauca', DEFAULT, DEFAULT);
INSERT INTO departamento VALUES ('Stdr', 'Santander', DEFAULT, DEFAULT);
INSERT INTO departamento VALUES ('Qdio', 'Quindío', DEFAULT, DEFAULT);
INSERT INTO departamento VALUES ('Rslda', 'Risaralda', DEFAULT, DEFAULT);
INSERT INTO departamento VALUES ('Ptyo', 'Putumayo', DEFAULT, DEFAULT);
INSERT INTO departamento VALUES ('Hul', 'Huila', DEFAULT, DEFAULT);
INSERT INTO departamento VALUES ('Cqta', 'Caquetá', DEFAULT, DEFAULT);
INSERT INTO departamento VALUES ('Byca', 'Boyacá', DEFAULT, DEFAULT);
INSERT INTO departamento VALUES ('Cund', 'Cundinamarca', DEFAULT, DEFAULT);
INSERT INTO departamento VALUES ('Tol', 'Tolima', DEFAULT, DEFAULT);
INSERT INTO departamento VALUES ('Mta', 'Meta', DEFAULT, DEFAULT);
INSERT INTO departamento VALUES ('Csnre', 'Casanare', DEFAULT, DEFAULT);
INSERT INTO departamento VALUES ('Cauc', 'Cauca', DEFAULT, DEFAULT);
INSERT INTO departamento VALUES ('Nrño', 'Nariño', DEFAULT, DEFAULT);
INSERT INTO departamento VALUES ('Antq', 'Antioquia', DEFAULT, DEFAULT);
INSERT INTO departamento VALUES ('Csr', 'Cesar', DEFAULT, DEFAULT);
INSERT INTO departamento VALUES ('Arc', 'Arauca', DEFAULT, DEFAULT);
INSERT INTO departamento VALUES ('Nstdr', 'Norte de Santander', DEFAULT, DEFAULT);
INSERT INTO departamento VALUES ('Blvr', 'Bolívar', DEFAULT, DEFAULT);
INSERT INTO departamento VALUES ('Gvre', 'Guaviare', DEFAULT, DEFAULT);
INSERT INTO departamento VALUES ('Vpes', 'Vaupés', DEFAULT, DEFAULT);
INSERT INTO departamento VALUES ('Amz', 'Amazonas', DEFAULT, DEFAULT);
INSERT INTO departamento VALUES ('Atl', 'Atlántico', DEFAULT, DEFAULT);
INSERT INTO departamento VALUES ('Chc', 'Chocó', DEFAULT, DEFAULT);
INSERT INTO departamento VALUES ('Vcha', 'Vichada', DEFAULT, DEFAULT);
INSERT INTO departamento VALUES ('Gna', 'Guainía', DEFAULT, DEFAULT);
INSERT INTO departamento VALUES ('Cdba', 'Córdoba', DEFAULT, DEFAULT);

INSERT INTO ciudad VALUES ('Bgta', 'Bogotá D.C.', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cal', 'Manizales', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cal', 'La Dorada', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cal', 'Marmato', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cal', 'Anserma', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cal', 'Chinchiná', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cal', 'Aguadas', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cal', 'Belalcázar', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cal', 'Filadelfia', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cal', 'Manzanares', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cal', 'Aranzazu', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cal', 'Marquetalia', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cal', 'La Merced', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cal', 'Villamaría', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cal', 'Riosucio', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cal', 'Pácora', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cal', 'Supía', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cal', 'Neira', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cal', 'Pensilvania', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cal', 'Marulanda', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cal', 'Viterbo', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cal', 'Samaná', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cal', 'Salamina', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cal', 'Palestina', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cal', 'Norcaisa', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cal', 'Risaralda', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cal', 'Victoria', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cal', 'San José', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cal', 'Norcasia', DEFAULT, DEFAULT);

INSERT INTO ciudad VALUES ('Vcauc', 'Alcalá', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Vcauc', 'Andalucía', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Vcauc', 'Ansermanuevo', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Vcauc', 'Argelia', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Vcauc', 'Bolívar', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Vcauc', 'Buenaventura', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Vcauc', 'Buga', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Vcauc', 'Bugalagrande', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Vcauc', 'Caicedonia', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Vcauc', 'Cali', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Vcauc', 'Calima - El Darién', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Vcauc', 'Candelaria', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Vcauc', 'Cartago', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Vcauc', 'Dagua', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Vcauc', 'El Águila', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Vcauc', 'El Cairo', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Vcauc', 'El Cerrito', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Vcauc', 'El Dovio', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Vcauc', 'Florida', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Vcauc', 'Ginebra', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Vcauc', 'Guacarí', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Vcauc', 'Jamundí', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Vcauc', 'La Cumbre', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Vcauc', 'La Unión', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Vcauc', 'La Victoria', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Vcauc', 'Obando', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Vcauc', 'Palmira', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Vcauc', 'Pradera', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Vcauc', 'Restrepo', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Vcauc', 'Riofrío', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Vcauc', 'Roldanillo', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Vcauc', 'San Pedro', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Vcauc', 'Sevilla', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Vcauc', 'Toro', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Vcauc', 'Trujillo', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Vcauc', 'Tuluá', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Vcauc', 'Ulloa', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Vcauc', 'Versalles', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Vcauc', 'Vijes', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Vcauc', 'Yotoco', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Vcauc', 'Yumbo', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Vcauc', 'Zarzal', DEFAULT, DEFAULT);

INSERT INTO ciudad VALUES ('Stdr', 'Piedecuesta', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Stdr', 'Aguada', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Stdr', 'Albania', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Stdr', 'Aratoca', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Stdr', 'Barbosa', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Stdr', 'Barichara', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Stdr', 'Barrancabermeja', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Stdr', 'Betulia', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Stdr', 'Bolívar', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Stdr', 'Bucaramanga', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Stdr', 'Cabrera', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Stdr', 'California', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Stdr', 'Capitanejo', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Stdr', 'Carcasí', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Stdr', 'Cepitá', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Stdr', 'Cerrito', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Stdr', 'Charalá', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Stdr', 'Charta', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Stdr', 'Chima', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Stdr', 'Chipatá', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Stdr', 'Cimitarra', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Stdr', 'El Peñon', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Stdr', 'Florián', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Stdr', 'Floridablanca', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Stdr', 'Galán', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Stdr', 'Gámbita', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Stdr', 'Guaca', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Stdr', 'Girón', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Stdr', 'Guadalupe', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Stdr', 'Jordán', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Stdr', 'La Belleza', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Stdr', 'Málaga', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Stdr', 'Mogotes', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Stdr', 'Ocamonte', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Stdr', 'Rionegro', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Stdr', 'San Andrés', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Stdr', 'San Benito', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Stdr', 'San Gil', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Stdr', 'San Joaquín', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Stdr', 'Simacota', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Stdr', 'Socorro', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Stdr', 'Suaita', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Stdr', 'Sucre', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Stdr', 'Suratá', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Stdr', 'Tona', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Stdr', 'Valle de San José', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Stdr', 'Vélez', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Stdr', 'Villanueva', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Stdr', 'Zapatoca', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Stdr', 'Puente Nacional', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Stdr', 'El Playón', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Stdr', 'San Juan de Girón', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Stdr', 'Puerto Wilches', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Stdr', 'Lebrija', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Stdr', 'San Vicente de Chicurí', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Stdr', 'El Carmen de Chucurí', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Stdr', 'Landázuri', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Stdr', 'Bolívar', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Stdr', 'Curití', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Stdr', 'Oiba', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Stdr', 'Los Santos', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Stdr', 'Puerto Parra', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Stdr', 'Los Santos', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Stdr', 'Cerrito', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Stdr', 'Coromoro', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Stdr', 'Concepción', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Stdr', 'Matanza', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Stdr', 'Onzaga', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Stdr', 'El Peñon', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Stdr', 'La Paz', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Stdr', 'Molagavita', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Stdr', 'San José de Miranda', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Stdr', 'Santa Helena de Opón', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Stdr', 'Guavatá', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Stdr', 'Güepsa', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Stdr', 'Enciso', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Stdr', 'Contratación', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Stdr', 'Pinchote', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Stdr', 'Páramo', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Stdr', 'Jesús María', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Stdr', 'Confines', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Stdr', 'Encino', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Stdr', 'Macaravita', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Stdr', 'San Miguel', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Stdr', 'Palmas del Socorro', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Stdr', 'San Miguel', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Stdr', 'Hato', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Stdr', 'Santa Bárbara', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Stdr', 'El Guacamayo', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Stdr', 'Guapotá', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Stdr', 'Palmar', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Stdr', 'Vetas', DEFAULT, DEFAULT);

INSERT INTO ciudad VALUES ('Qdio', 'Armenia', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Qdio', 'Buenavista', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Qdio', 'Calarcá', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Qdio', 'Circasia', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Qdio', 'Córdoba', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Qdio', 'Filandia', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Qdio', 'Génova', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Qdio', 'La Tebaida', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Qdio', 'Montenegro', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Qdio', 'Pijao', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Qdio', 'Quimbaya', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Qdio', 'Salento', DEFAULT, DEFAULT);

INSERT INTO ciudad VALUES ('Rslda', 'Apía', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Rslda', 'Balboa', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Rslda', 'Bélen de Umbría', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Rslda', 'Dosquebradas', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Rslda', 'Guática', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Rslda', 'La Celia', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Rslda', 'La Virginia', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Rslda', 'Marsella', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Rslda', 'Mistrató', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Rslda', 'Pereira', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Rslda', 'Pueblo Rico', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Rslda', 'Quinchía', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Rslda', 'Santa Rosa de Cabal', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Rslda', 'Santuario', DEFAULT, DEFAULT);

INSERT INTO ciudad VALUES ('Cqta', 'Florencia', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cqta', 'Puerto Rico', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cqta', 'Morelia', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cqta', 'Valparaiso', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cqta', 'Belén de los Andaquíes', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cqta', 'Cartagena del Chairá', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cqta', 'Curillo', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cqta', 'El Doncello', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cqta', 'El Paujil', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cqta', 'La Montañita', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cqta', 'Puerto Milán', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cqta', 'Puerto Rico', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cqta', 'San José del Fragua', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cqta', 'San Vicente del Caguán', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cqta', 'Solano', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cqta', 'Solita', DEFAULT, DEFAULT);

INSERT INTO ciudad VALUES ('Ptyo', 'Puerto Asis', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Ptyo', 'Puerto Leguizamo', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Ptyo', 'Mocoa', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Ptyo', 'Villagarzón', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Ptyo', 'Puerto Caicedo', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Ptyo', 'Orito', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Ptyo', 'Valle del Guamuez', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Ptyo', 'Puerto Guzmán', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Ptyo', 'San Miguel', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Ptyo', 'Sibundoy', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Ptyo', 'Colón', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Ptyo', 'Santiago', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Ptyo', 'San Francisco', DEFAULT, DEFAULT);

INSERT INTO ciudad VALUES ('Hul', 'Neiva', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Hul', 'Suaza', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Hul', 'Isnos', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Hul', 'Algeciras', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Hul', 'Villavieja', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Hul', 'La argentina', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Hul', 'Tesalia', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Hul', 'Timana', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Hul', 'Campoalegre', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Hul', 'Altamira', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Hul', 'Pitalito', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Hul', 'Baraya', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Hul', 'Hobo', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Hul', 'San Agustin', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Hul', 'Teruel', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Hul', 'Yaguara', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Hul', 'Aipe', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Hul', 'Tarqui', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Hul', 'Tello', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Hul', 'Garzon', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Hul', 'Rivera', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Hul', 'Acevedo', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Hul', 'Guadalupe', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Hul', 'Palermo', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Hul', 'Santa María', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Hul', 'Palestina', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Hul', 'El Agrado', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Hul', 'El Pital', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Hul', 'Gigante', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Hul', 'Paicol', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Hul', 'Nátaga', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Hul', 'La Plata', DEFAULT, DEFAULT);

INSERT INTO ciudad VALUES ('Byca', 'Tunja', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Byca', 'Boyacá', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Byca', 'Duitama', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Byca', 'Moniquirá', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Byca', 'Chiquinquirá', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Byca', 'Paipa', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Byca', 'Villa de Leyva', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Byca', 'Puerto Boyacá', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Byca', 'Monguí', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Byca', 'Ventaquemada', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Byca', 'Otanche', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Byca', 'Cómbita', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Byca', 'Tibabosa', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Byca', 'Toca', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Byca', 'Corrales', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Byca', 'Ráquira', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Byca', 'Tenza', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Byca', 'Iza', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Byca', 'Nobsa', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Byca', 'Santa Rosa de Viterbo', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Byca', 'Mongua', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Byca', 'Saboyá', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Byca', 'Garagoa', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Byca', 'Muzo', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Byca', 'Motavita', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Byca', 'Sáchica', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Byca', 'Tuta', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Byca', 'Chita', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Byca', 'Socotá', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Byca', 'Miraflores', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Byca', 'El Cocuy', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Byca', 'Caldas', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Byca', 'Pauna', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Byca', 'Samacá', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Byca', 'Guateque', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Byca', 'Chivata', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Byca', 'Ramiriquí', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Byca', 'Úmbita', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Byca', 'Aquitania', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Byca', 'Pisba', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Byca', 'Zetaquira', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Byca', 'Tibaná', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Byca', 'Sativasur', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Byca', 'Soatá', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Byca', 'Soracá', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Byca', 'Tasco', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Byca', 'Pesca', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Byca', 'Sutarmarchán', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Byca', 'Socha', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Byca', 'Siachoque', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Byca', 'Campohermoso', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Byca', 'Jenesano', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Byca', 'Tierranegra', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Byca', 'Arcabuco', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Byca', 'Belén', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Byca', 'La Primavera', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Byca', 'Santa Rosalia', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Byca', 'Norcasia', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Byca', 'Panqueba', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Byca', 'Togui', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Byca', 'Nuevo Colón', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Byca', 'La Uvita', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Byca', 'Sutatenza', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Byca', 'Firavitoba', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Byca', 'Sogamoso', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Byca', 'Tipacoque', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Byca', 'Cerinza', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Byca', 'Santa Sofía', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Byca', 'Tenza', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Byca', 'Sutatenza', DEFAULT, DEFAULT);

INSERT INTO ciudad VALUES ('Cund', 'Soacha', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'San Francisco', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Chía', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Melgar', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Pasca', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Subachoque', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Cogua', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Guapota', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Cabrera', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Silvania', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Cajicá', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Chipaque', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'La Vega', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Bogotá', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Zipaquirá', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Sutatausa', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Fusagasugá', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Girardot', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Facatativá', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Tocaima', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Villeta', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'La Calera', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Mosquera', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Anolaima', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Guatavita', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Apulo', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Funza', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Cota', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Sasaima', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'La Mesa', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Madrid', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Nilo', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Quebradanegra', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Ricaurte', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Supata', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Vergara', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Quipile', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Guaduas', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Bojacá', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Zipacón', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Sopo', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'La Pena', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Útica', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Gachancipá', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Tocancipá', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Cáqueza', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Agua de Dios', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Chaguani', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Arbeláez', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Viotá', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'San Antonio Del Tequendama', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Chocontá', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Tibacuy', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Nimaima', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Albán', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'El Rosal', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Sesquilé', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Guataquí', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Une', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Ubaté', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Anapoima', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Caparrapí', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Guayabal de Síquima', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Nemocón', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Tena', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Villapinzón', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Paratebueno', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Puerto Salgar', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Chía', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Medina', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Gutiérrez', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Tibirita', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Pulí', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Jerusalén', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Bituima', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Villagómez', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Nariño', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Beltrán', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Gama', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'El Peñon', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Paime', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Fúquene', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Supatá', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Tausa', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Guayabetal', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Topaipí', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Cabrera', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Quebradanegra', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Manta', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Vianí', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Sibaté', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Pacho', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Sopó', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Tabio', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'El Colegio', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Tenjo', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Yacopí', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Suesca', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Guasca', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Fómeque', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Ubalá', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Guachetá', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Choachí', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Simijaca', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Gachetá', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'San Bernardo', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Susa', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Cachipay', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Lenguazaque', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'San Juan de Rioseco', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Junín', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Granada', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'La Peña', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Cucunubá', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Ubaque', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Machetá', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Fosca', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Quetame', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Gachalá', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Pandi', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'Nocaima', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'San Cayetano', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cund', 'El Peñón', DEFAULT, DEFAULT);

INSERT INTO ciudad VALUES ('Tol', 'Ibagué', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Tol', 'Falan', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Tol', 'Mariquita', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Tol', 'Líbano', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Tol', 'El Espinal', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Tol', 'Honda', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Tol', 'Alvarado', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Tol', 'Venadillo', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Tol', 'Chaparral', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Tol', 'Ataco', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Tol', 'Saldaña', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Tol', 'Rovira', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Tol', 'Villahermosa', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Tol', 'Fresno', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Tol', 'Planadas', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Tol', 'Ortega', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Tol', 'Cajamarca', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Tol', 'Rioblanco', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Tol', 'Natagaima', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Tol', 'Palocabildo', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Tol', 'Coello', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Tol', 'Guamo', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Tol', 'Lérida', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Tol', 'Herveo', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Tol', 'Flandes', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Tol', 'Purificación', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Tol', 'Ambalema', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Tol', 'Cunday', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Tol', 'Casablanca', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Tol', 'Anzoátegui', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Tol', 'Villarica', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Tol', 'Coyaima', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Tol', 'Armero', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Tol', 'San Antonio', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Tol', 'Murillo', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Tol', 'Alpujarra', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Tol', 'Valle de San Juan', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Tol', 'Ronces Valles', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Tol', 'Melgar', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Tol', 'Santa Isabel', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Tol', 'Icononzo', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Tol', 'San Luis', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Tol', 'Prado', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Tol', 'Dolores', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Tol', 'Carmen de Apicalá', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Tol', 'Suarez', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Tol', 'Guayabal', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Tol', 'Piedras', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Tol', 'Falán', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Tol', 'Casabianca', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Tol', 'Roncesvalles', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Tol', 'Villarrica', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Tol', 'Suárez', DEFAULT, DEFAULT);

INSERT INTO ciudad VALUES ('Mta', 'Villavicencio', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Mta', 'El Castillo', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Mta', 'Acacías', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Mta', 'San Juan de Arama', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Mta', 'Mesetas', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Mta', 'Vistahermosa', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Mta', 'Puerto Lleras', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Mta', 'Lejanías', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Mta', 'La Macarena', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Mta', 'Cubarral', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Mta', 'La Uribe', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Mta', 'Fuente de Oro', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Mta', 'Guamal', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Mta', 'Cumaral', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Mta', 'Castilla la Nueva', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Mta', 'El Calvario', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Mta', 'Puerto López', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Mta', 'Puerto Rico', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Mta', 'San Martín', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Mta', 'Granada', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Mta', 'Restrepo', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Mta', 'Puerto Gaitán', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Mta', 'Mapiripán', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Mta', 'Puerto Concordia', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Mta', 'Cabuyaro', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Mta', 'San Juanito', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Mta', 'Barranca', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Mta', 'San Carlos Guaroa', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Mta', 'El Dorado', DEFAULT, DEFAULT);

INSERT INTO ciudad VALUES ('Csnre', 'Yopal', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Csnre', 'Aguazul', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Csnre', 'Pore', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Csnre', 'Tauramena', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Csnre', 'Nunchía', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Csnre', 'Hato Corozal', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Csnre', 'Tamará', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Csnre', 'Orocué', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Csnre', 'Chámeza', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Csnre', 'Paz de Ariporo', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Csnre', 'San Luís de Palenque', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Csnre', 'Sabanalarga', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Csnre', 'Sácama', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Csnre', 'Recetor', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Csnre', 'Monterrey', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Csnre', 'La Salina', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Csnre', 'Villanueva', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Csnre', 'Trinidad', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Csnre', 'Maní', DEFAULT, DEFAULT);

INSERT INTO ciudad VALUES ('Cauc', 'Popayán', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cauc', 'Caloto', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cauc', 'Toribio', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cauc', 'Jambaló', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cauc', 'Puerto Tejada', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cauc', 'Corinto', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cauc', 'Cajibío', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cauc', 'Santander de Quilichao', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cauc', 'Patía', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cauc', 'Sotará', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cauc', 'Guachené', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cauc', 'Buenos Aires', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cauc', 'Coconuco', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cauc', 'Padilla', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cauc', 'Balboa', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cauc', 'Morales', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cauc', 'Totoró', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cauc', 'Timbío', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cauc', 'El Bordo', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cauc', 'Silvia', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cauc', 'Bolívar', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cauc', 'Almaguer', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cauc', 'El Tambo', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cauc', 'Inza', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cauc', 'Mercaderes', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cauc', 'Piendamó', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cauc', 'La Vega', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cauc', 'Villa Rica', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cauc', 'Belalcazar', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cauc', 'Guapi', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cauc', 'La Sierra', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cauc', 'Miranda', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cauc', 'Timbiquí', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cauc', 'Micay', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cauc', 'Florencia', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cauc', 'Santa Rosa', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cauc', 'San Sebastián', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cauc', 'Piamonte', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cauc', 'Cali', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cauc', 'Rosas', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cauc', 'Argelia', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cauc', 'Sucre', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cauc', 'Suárez', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cauc', 'Jamundí', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cauc', 'Palmira', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cauc', 'Riofrío', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cauc', 'Buga', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cauc', 'Candelaria', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cauc', 'Pradera', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cauc', 'Tuluá', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cauc', 'Trujillo', DEFAULT, DEFAULT);

INSERT INTO ciudad VALUES ('Nrño', 'Pasto', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nrño', 'Ipiales', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nrño', 'Tumaco', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nrño', 'Túquerres', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nrño', 'Sandoná', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nrño', 'Samaniego', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nrño', 'Yacuanquer', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nrño', 'Cumbal', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nrño', 'Taminango', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nrño', 'El Tambo', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nrño', 'Consaca', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nrño', 'La Florida', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nrño', 'Buesaco', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nrño', 'Tangua', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nrño', 'Chachagüí', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nrño', 'Ricaurte', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nrño', 'Ospina', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nrño', 'El Charco', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nrño', 'Magüí Payán', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nrño', 'El Tablón de Gómez', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nrño', 'Roberto Payan', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nrño', 'Guaitarilla', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nrño', 'Funes', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nrño', 'Policarpa', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nrño', 'La Cruz', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nrño', 'Sapuyes', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nrño', 'Linares', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nrño', 'Guachucal', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nrño', 'Olaya Herrera', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nrño', 'Ancuya', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nrño', 'El Rosario', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nrño', 'Pupiales', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nrño', 'La Llanada', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nrño', 'Barbacoas', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nrño', 'Alban', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nrño', 'La Tola', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nrño', 'Potosí', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nrño', 'Mosquera', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nrño', 'Puerres', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nrño', 'Gualmatán', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nrño', 'Iles', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nrño', 'Santacruz', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nrño', 'Iscuande', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nrño', 'Leiva', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nrño', 'Aldana', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nrño', 'Arboleda', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nrño', 'Piedrancha', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nrño', 'Carlosama', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nrño', 'La Unión', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nrño', 'Córdoba', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nrño', 'San Bernardo', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nrño', 'San José de Albán', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nrño', 'San Lorenzo', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nrño', 'Roberto Payán', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nrño', 'San Pablo', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nrño', 'Los Andes', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nrño', 'Providencia', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nrño', 'Francisco Pizarro', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nrño', 'Consacá', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nrño', 'Colón', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nrño', 'Santa Bárbara', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nrño', 'Mallama', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nrño', 'Ancuyá', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nrño', 'Cuaspud', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nrño', 'San Pedro de Cartago', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nrño', 'El Peñol', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nrño', 'Belén', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nrño', 'Nariño', DEFAULT, DEFAULT);

INSERT INTO ciudad VALUES ('Antq', 'Medellín', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Antq', 'Yolombo', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Antq', 'Granada', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Antq', 'Bello', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Antq', 'Envigado', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Antq', 'Santa Rosa de Osos', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Antq', 'Remedios', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Antq', 'La Estrella', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Antq', 'Apartadó', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Antq', 'Santa Fé de Antioquia', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Antq', 'Sonsón', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Antq', 'Amalfi', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Antq', 'Ciudad Bolívar', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Antq', 'Jardín', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Antq', 'Itagüí', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Antq', 'Barbosa', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Antq', 'Turbo', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Antq', 'Caldas', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Antq', 'Sabaneta', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Antq', 'San Carlos', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Antq', 'Rionegro', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Antq', 'Puerto Berrío', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Antq', 'Marinilla', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Antq', 'La Ceja', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Antq', 'Santo Domingo', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Antq', 'Peñol', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Antq', 'La Pintada', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Antq', 'Salgar', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Antq', 'Arboletes', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Antq', 'Buriticá', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Antq', 'San Vicente', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Antq', 'Valdivia', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Antq', 'Necoclí', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Antq', 'Guatape', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Antq', 'Carepa', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Antq', 'Frontino', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Antq', 'Peque', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Antq', 'Nariño', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Antq', 'San Luís', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Antq', 'Sopetrán', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Antq', 'Betulia', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Antq', 'Angelópolis', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Antq', 'Abejorral', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Antq', 'Abriaqui', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Antq', 'Anza', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Antq', 'Venecia', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Antq', 'Retiro', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Antq', 'Fredonia', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Antq', 'Concepción', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Antq', 'San Pedro', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Antq', 'Caramanta', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Antq', 'Caicedo', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Antq', 'Valparaiso', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Antq', 'Carmen de Viboral', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Antq', 'Segovia', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Antq', 'Antioquia', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Antq', 'Antioquia', DEFAULT, DEFAULT);

INSERT INTO ciudad VALUES ('Csr', 'Valledupar', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Csr', 'Aguachica', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Csr', 'Curumaní', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Csr', 'El Paso', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Csr', 'La Jagüa de Ibirico', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Csr', 'San Diego', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Csr', 'Agustín Codazzi', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Csr', 'Pelaya', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Csr', 'Pueblo Bello', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Csr', 'San Alberto', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Csr', 'Astrea', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Csr', 'Gamarra', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Csr', 'Chimichagua', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Csr', 'Chiriguaná', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Csr', 'La Paz Robles', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Csr', 'Becerril', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Csr', 'El Copey', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Csr', 'San Martín', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Csr', 'Manaure Balcón del Cesar', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Csr', 'La Gloria', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Csr', 'Pailitas', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Csr', 'Río de Oro', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Csr', 'Tamalameque', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Csr', 'González', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Csr', 'Bosconia', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Csr', 'Valencia de Jesús', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Csr', 'San Juan del Cesar', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Csr', 'El Banco', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Csr', 'Guatapurí', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Csr', 'El Molino', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Csr', 'Ariguani', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Csr', 'El Peñón', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Csr', 'Gamarra', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Csr', 'Los Háticos', DEFAULT, DEFAULT);

INSERT INTO ciudad VALUES ('Arc', 'Villa de Santa Bárbara de Arauca', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Arc', 'Saravena', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Arc', 'Fortul', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Arc', 'Puerto Rondón', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Arc', 'Cravo Norte', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Arc', 'Arauquita', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Arc', 'Tame', DEFAULT, DEFAULT);

INSERT INTO ciudad VALUES ('Nstdr', 'Cúcuta', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nstdr', 'Ocaña', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nstdr', 'Pamplona', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nstdr', 'La Troja', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nstdr', 'Sardinata', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nstdr', 'Arboledas', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nstdr', 'Convención', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nstdr', 'Villa del Rosario', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nstdr', 'Teorama', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nstdr', 'Hacarí', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nstdr', 'Abrego', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nstdr', 'San Calixto', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nstdr', 'Cucutilla', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nstdr', 'Bochalema', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nstdr', 'Durania', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nstdr', 'Cachira', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nstdr', 'El Zulia', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nstdr', 'Tibú', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nstdr', 'Salazar', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nstdr', 'Gramalote', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nstdr', 'Labateca', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nstdr', 'Ragonvalia', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nstdr', 'El Tarra', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nstdr', 'Pamplonita', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nstdr', 'Chitaga', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nstdr', 'Herrán', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nstdr', 'Chinácota', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nstdr', 'San Cayetano', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nstdr', 'Mutiscua', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nstdr', 'Puerto Santander', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nstdr', 'La Playa', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nstdr', 'Bucarasica', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nstdr', 'Villa Caro', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nstdr', 'Cácota', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nstdr', 'Silos', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nstdr', 'Los Patios', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nstdr', 'Toledo', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nstdr', 'La Esperanza', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nstdr', 'Lourdes', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nstdr', 'Bucaramanga', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nstdr', 'Santiago', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nstdr', 'Abrego', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nstdr', 'Área Metropolitana Cúcuta', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nstdr', 'El Tarra', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nstdr', 'Vetas', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nstdr', 'Málaga', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nstdr', 'Matanza', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Nstdr', 'Charta', DEFAULT, DEFAULT);

INSERT INTO ciudad VALUES ('Blvr', 'Cartagena', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Blvr', 'Magangué', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Blvr', 'Simití', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Blvr', 'El Carmen de Bolívar', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Blvr', 'Santa Rosa del Sur', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Blvr', 'Arenal', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Blvr', 'María la Baja', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Blvr', 'Arjona', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Blvr', 'San Pablo', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Blvr', 'San Jacinto', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Blvr', 'Morales', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Blvr', 'Turbaco', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Blvr', 'Santa Rosa', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Blvr', 'Santa Cruz de Mompox', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Blvr', 'Cantagallo', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Blvr', 'Río Viejo', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Blvr', 'Achí', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Blvr', 'San Estanislao', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Blvr', 'Turbana', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Blvr', 'San Juán Nepomuceno', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Blvr', 'Mompós', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Blvr', 'Villanueva', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Blvr', 'Tiquisio', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Blvr', 'Zambrano', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Blvr', 'San Martín de Loba', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Blvr', 'Norosi', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Blvr', 'Santa Catalina', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Blvr', 'Montecristo', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Blvr', 'Regidor', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Blvr', 'Pinillos', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Blvr', 'El Guamo', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Blvr', 'Barranca de Loba', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Blvr', 'Mahates', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Blvr', 'Córdoba', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Blvr', 'Clemencia', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Blvr', 'Calamar', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Blvr', 'Altos del Rosario', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Blvr', 'San Jacinto del Cauca', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Blvr', 'Soplaviento', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Blvr', 'Arroyohondo', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Blvr', 'El Peñon', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Blvr', 'San Fernando', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Blvr', 'Cicuco', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Blvr', 'Talaigua Nuevo', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Blvr', 'Hatillo de Loba', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Blvr', 'San Cristóbal', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Blvr', 'Margarita', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Blvr', 'Barranco de Loba', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Blvr', 'Brazuelo de Papayal', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Blvr', 'Norosí', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Blvr', 'Turbaná', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Blvr', 'El Peñon', DEFAULT, DEFAULT);

INSERT INTO ciudad VALUES ('Gvre', 'San José del Guaviare', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Gvre', 'El Retorno', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Gvre', 'Calamar', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Gvre', 'Miraflores', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Gvre', 'Mapiripán', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Gvre', 'Puerto Concordia', DEFAULT, DEFAULT);

INSERT INTO ciudad VALUES ('Vpes', 'Mitú', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Vpes', 'Yavarate', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Vpes', 'Acaricuara', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Vpes', 'Taraira', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Vpes', 'Papunahua', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Vpes', 'Miraflores', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Vpes', 'Carurú', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Vpes', 'Pacoa', DEFAULT, DEFAULT);

INSERT INTO ciudad VALUES ('Amz', 'Leticia', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Amz', 'Puerto Nariño', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Amz', 'El Encanto', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Amz', 'La Pedrera', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Amz', 'La Chorrera', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Amz', 'Tarapacá', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Amz', 'Puerto Santander', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Amz', 'Mirití-Paraná', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Amz', 'Puerto Alegría', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Amz', 'Puerto Arica', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Amz', 'La Victoria', DEFAULT, DEFAULT);

INSERT INTO ciudad VALUES ('Atl', 'Barranquilla', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Atl', 'Soledad', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Atl', 'Malambo', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Atl', 'Sabanalarga', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Atl', 'Baranoa', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Atl', 'Galapa', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Atl', 'Puerto Colombia', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Atl', 'Sabanagrande', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Atl', 'Santo Tomás', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Atl', 'Palmar de Varela', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Atl', 'Luruago', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Atl', 'Repelón', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Atl', 'Ponedera', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Atl', 'Campo De La Cruz', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Atl', 'Juan de Acosta', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Atl', 'Polonuevo', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Atl', 'Manatí', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Atl', 'Santa Lucía', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Atl', 'Candelaria', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Atl', 'Tubará', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Atl', 'Suán', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Atl', 'Usiacurí', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Atl', 'Piojó', DEFAULT, DEFAULT);

INSERT INTO ciudad VALUES ('Chc', 'Quibdó', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Chc', 'Alto Baudó', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Chc', 'Istmina', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Chc', 'Tadó', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Chc', 'Bajo Baudó', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Chc', 'Riosucio', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Chc', 'Condoto', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Chc', 'Unguía', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Chc', 'Medio San Juan', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Chc', 'Medio Baudó', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Chc', 'Acandí', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Chc', 'Medio Atrato', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Chc', 'Bojayá', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Chc', 'Bahía Solano', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Chc', 'Bagadó', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Chc', 'Lloró', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Chc', 'Litoral de San Juan', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Chc', 'El Carmen de Atrato', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Chc', 'Cértegui', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Chc', 'Nuquí', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Chc', 'Río Quito', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Chc', 'Rio Íro', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Chc', 'Nóvita', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Chc', 'Unión Panamericana', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Chc', 'Atrato', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Chc', 'Cantón de San Pablo', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Chc', 'El Carmen del Darién', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Chc', 'San José de Palmar', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Chc', 'Sipí', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Chc', 'Juradó', DEFAULT, DEFAULT);

INSERT INTO ciudad VALUES ('Vcha', 'Cumaribo', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Vcha', 'Puerto Carreño', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Vcha', 'La Primavera', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Vcha', 'Santa Rosalía', DEFAULT, DEFAULT);

INSERT INTO ciudad VALUES ('Gna', 'Inírida', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Gna', 'Barranco Minas', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Gna', 'Mapiripana', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Gna', 'Pana Pana', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Gna', 'Cacahual', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Gna', 'San Felipe', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Gna', 'Puerto Colombia', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Gna', 'Morichal Nuevo', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Gna', 'La Guadalupe', DEFAULT, DEFAULT);

INSERT INTO ciudad VALUES ('Cdba', 'Montería', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cdba', 'Santa Cruz de Lorica', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cdba', 'Sahagún', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cdba', 'Cereté', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cdba', 'Tierralta', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cdba', 'Montelíbano', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cdba', 'San Andrés de Sotaviento', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cdba', 'Planeta Rica', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cdba', 'Ciénaga de Oro', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cdba', 'Chinú', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cdba', 'Ayapel', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cdba', 'San Pelayo', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cdba', 'Valencia', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cdba', 'Puerto Libertador', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cdba', 'Tuchín', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cdba', 'Pueblo Nuevo', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cdba', 'San Bernando del Viento', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cdba', 'San Antero', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cdba', 'San Carlos', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cdba', 'Moñitos', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cdba', 'Puerto Escondido', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cdba', 'Buenavista', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cdba', 'Los Córdobas', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cdba', 'Cotorra', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cdba', 'Purísima', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cdba', 'Canalete', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cdba', 'Momil', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cdba', 'Chimá', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cdba', 'La Apartada', DEFAULT, DEFAULT);
INSERT INTO ciudad VALUES ('Cdba', 'San José de Úre', DEFAULT, DEFAULT);
